version: '3.8'

services:
  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app
    environment:
      - ELASTICSEARCH_URL=http://host.docker.internal:9200
    # depends_on:
    #   - elasticsearch
    volumes:
      - ./data:/app/data
    networks:
      - esnet

networks:
  esnet:
    driver: bridge
